# Generated by Django 5.0.6 on 2024-06-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='dealer_number',
            field=models.IntegerField(),
        ),
    ]
