# Generated by Django 5.0.6 on 2024-06-21 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dealer_dealer_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_code', models.IntegerField(max_length=10)),
                ('medicine_name', models.CharField(max_length=20)),
                ('medicine_price', models.IntegerField(max_length=10)),
                ('medicine_stock', models.IntegerField(max_length=10)),
                ('medicine_desc', models.CharField(max_length=20)),
                ('medicine_dealer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dealer')),
            ],
        ),
    ]
