# Generated by Django 5.0.6 on 2024-06-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medicine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['medicine_code']},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_code',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
