# Generated by Django 5.0.6 on 2024-06-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_medicine_options_alter_medicine_medicine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_stock',
            field=models.IntegerField(),
        ),
    ]
