# Generated by Django 5.0.6 on 2024-06-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_alter_dealer_dealer_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
